[workspace]
members = ["shared", "api-gateway-service", "authentication-service", "fulfillment-service", "logging-service", "notifications-service"]

resolver = "2"

[workspace.dependencies]
tokio = { version = "1.47.1", features = ["full"]}
serde = { version = "1.0.228", features = ["derive"]}
