[package]
name = "logging-service"
version = "0.1.0"
edition = "2021"

[dependencies]
# Crate Dependencies

# Workspace Dependencies
serde = { workspace = true}
serde_json = { workspace = true}
tokio = { workspace = true }